name: Release

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: npmjs:@sap/mdk-mcp-server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Check npm version
        run: |
          echo "Current npm version: $(npm --version)"
          echo "Latest npm version: $(npx npm@latest --version)"
      - name: Set instrumentation key in mdk-mcp-server
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: packages/mdk-mcp-server/src/telemetry/index.ts
          find: 'ApplicationInsightsInstrumentationKeyPLACEH0LDER'
          replace: ${{ secrets.INSTRUMENTATION_KEY }}
          regex: false  
      - name: run tests
        run: |
          npm i --include=optional
          npm run build
          npm test
      - name: get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.2.3
      - name: parse changelog
        id: parse-changelog
        uses: schwma/parse-changelog-action@v1.0.0
        with:
          version: '${{ steps.package-version.outputs.current-version }}'
      - name: create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ steps.package-version.outputs.current-version }}'
          body: '${{ steps.parse-changelog.outputs.body }}'
      - run: npx npm@latest publish --access public
